(function(){
 'use strict';
 const root=document.getElementById('cp-dev');if(!root||root.dataset.initialized)return;root.dataset.initialized='true';
 const github='https://github.com/Adil-Amin-Chishty/';
 const projects=[
  {id:'asa',title:'ASA Battery Plus',category:['web','mobile'],label:'STOREFRONT / WEB APP',image:'__ASA__',alt:'ASA Battery Plus live battery showroom',description:'A battery showroom with a searchable catalog and a private, installable mobile admin app.',tags:['Next.js','TypeScript','libSQL','PWA'],repo:'asa-battery-plus-website',live:'https://asa-battery-plus.netlify.app',detail:'A complete retail and wholesale browsing experience backed by a catalog that the shop owner can update without a redeploy.',features:['Search and filter battery models by brand, capacity and application.','Manage products, prices and visibility in a protected admin panel.','Upload product photos with browser-based background removal.','Install the admin web app on a mobile home screen.']},
  {id:'shop',title:'Shahzaib Milk Shop',category:['web','mobile'],label:'MOBILE-FIRST / ORDERING',image:'__SHOP__',alt:'Shahzaib Milk Shop live responsive ordering website',description:'A mobile-first storefront that turns a product basket into a ready-to-send WhatsApp pickup order.',tags:['Next.js','TypeScript','Tailwind CSS'],repo:'local-shop-ordering-system',live:'https://local-shop-ordering-system.vercel.app/',detail:'A demo storefront designed for local pickup orders. The customer browses the catalog, builds a basket and reviews a prepared message in WhatsApp.',features:['Browse product categories and adjust item quantities.','Keep the basket between visits with local browser storage.','Create a WhatsApp order message for customer review.','Responsive layouts for phones, tablets and desktop.']},
  {id:'portfolio',title:'Chishty, frame by frame',category:['web'],label:'PORTFOLIO / BRAND WEBSITE',image:'__CHEEZIOUS__',alt:'Chishty Productions live video editing portfolio website',description:'A branded portfolio with interactive video samples and a native project-enquiry workflow.',tags:['JavaScript','Responsive CSS','Systeme.io'],repo:'Video-Editing-Portfolio',live:'https://adilchisty963.systeme.io/630c665e',detail:'The Chishty Productions video-editing website connects a visual portfolio with a practical enquiry flow.',features:['Filter real video samples by format.','Open on-demand Google Drive video players.','Responsive layouts and reduced-motion support.','Native Systeme.io email enquiry and project brief flow.']},
  {id:'heads',title:'Heads Up',category:['interactive','mobile'],label:'INTERACTIVE / BROWSER GAME',image:'__HEADS__',alt:'Heads Up coin puzzle game',description:'A coin-flipping puzzle with animated interactions, difficulty levels and an optimal-solution helper.',tags:['JavaScript','HTML5','CSS3'],repo:'Heads-up-Game',live:'https://adil-amin-chishty.github.io/Heads-up-Game/',detail:'A browser puzzle where players flip consecutive coins to turn every coin to heads, balancing simple rules with a challenging solution.',features:['Multiple difficulty levels and move tracking.','Animated coin flips and victory effects.','Auto-solve helper for the optimal solution.','Responsive game interface with optional audio.']},
  {id:'racing',title:'Just Drive',category:['interactive'],label:'INTERACTIVE / RACING',image:'https://raw.githubusercontent.com/Adil-Amin-Chishty/Portfolio/main/Images/2D%20Racing%20Game.png',alt:'Just Drive 2D racing game project screenshot',description:'A browser-based 2D racing project built with HTML, CSS and JavaScript.',tags:['JavaScript','Canvas','HTML5'],repo:'Just-Drive-2D-Racing-Game',detail:'An arcade racing project exploring real-time browser interactions and canvas rendering.',features:['A 2D browser game built around a real-time game loop.','Custom game presentation and interactive controls.','Source code available on GitHub.']}
 ];
 const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const arrow='<i data-lucide="arrow-up-right"></i>';
 const links=p=>`<div class="project-links">${p.live?`<a href="${p.live}" target="_blank" rel="noopener">Live demo ${arrow}</a>`:''}<a href="${github+p.repo}" target="_blank" rel="noopener">Source code <i data-lucide="github"></i></a></div>`;
 root.querySelector('#project-grid').innerHTML=projects.map((p,i)=>`<article class="project" data-category="${p.category.join(' ')}"><div class="project-image"><img src="${p.image}" alt="${p.alt}" loading="lazy"><button class="project-open" data-project="${p.id}" aria-label="Explore ${p.title}" title="Explore ${p.title}">${arrow}</button></div><div class="project-meta"><h3>${p.title}</h3><span>0${i+1} / ${p.label}</span></div><p>${p.description}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div>${links(p)}</article>`).join('');
 function icons(){if(window.lucide)window.lucide.createIcons();}icons();
 root.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{root.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));root.querySelectorAll('.project').forEach(p=>{p.hidden=b.dataset.filter!=='all'&&!p.dataset.category.split(' ').includes(b.dataset.filter);p.classList.add('in');});if(window.cpProjectJourney)window.cpProjectJourney.reset();}));
 const dialog=root.querySelector('#project-dialog');
 root.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>{const p=projects.find(p=>p.id===b.dataset.project);root.querySelector('#dialog-content').innerHTML=`<p class="eyebrow">${p.label}</p><h2 id="dialog-title">${esc(p.title)}</h2><img src="${p.image}" alt="${p.alt}"><p>${p.detail}</p><ul>${p.features.map(t=>`<li>${t}</li>`).join('')}</ul>${links(p)}`;icons();dialog.showModal();}));
 root.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 if(!reduced){
  const grid=root.querySelector('#project-grid'),journey=document.createElement('div'),stage=document.createElement('div'),rail=document.createElement('nav');
  journey.className='project-journey';stage.className='journey-stage';rail.className='journey-rail';rail.setAttribute('aria-label','Project timeline');
  grid.before(journey);journey.append(stage);stage.append(grid,rail);grid.classList.add('depth-grid');
  const cards=Array.from(grid.children);let shown=cards,position=0,active=-1,queued=false;
  function go(index){const top=journey.getBoundingClientRect().top+scrollY;window.scrollTo({top:top+index*innerHeight*.95,behavior:'smooth'});}
  function draw(){queued=false;const max=shown.length-1,target=Math.max(0,Math.min(max,-journey.getBoundingClientRect().top/(innerHeight*.95)));position=target;
   const current=Math.min(max,Math.floor(position+.5));
   shown.forEach((card,i)=>{const d=i-position,out=Math.max(0,-d),incoming=Math.max(0,d),opacity=d<0?Math.max(0,1-out*1.3):Math.max(0,1-incoming*1.3);card.style.transform=`translate3d(${d<0?-out*320:incoming*210}px,${d<0?-out*85:incoming*90}px,${d<0?-out*1500:-incoming*900}px) rotateY(${d<0?out*22:-incoming*13}deg)`;card.style.opacity=opacity;card.style.zIndex=String(20-Math.abs(Math.round(d*10)));card.style.pointerEvents=i===current?'auto':'none';card.dataset.current=String(i===current);card.inert=i!==current;card.setAttribute('aria-hidden',String(i!==current));});
   if(active!==current){active=current;grid.dataset.activeProject=shown[current].querySelector('h3').textContent;rail.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-current',i===current?'step':'false'));}
  }
  function request(){if(!queued){queued=true;requestAnimationFrame(draw);}}
  function reset(){shown=cards.filter(c=>!c.hidden);active=-1;journey.style.height=`${100+Math.max(0,shown.length-1)*95}svh`;rail.innerHTML=shown.map((c,i)=>`<button aria-label="Go to ${esc(c.querySelector('h3').textContent)}" title="${esc(c.querySelector('h3').textContent)}"><span>0${i+1}</span></button>`).join('');rail.querySelectorAll('button').forEach((b,i)=>b.addEventListener('click',()=>go(i)));if(journey.getBoundingClientRect().top<0)go(0);draw();}
  addEventListener('scroll',request,{passive:true});addEventListener('resize',request);window.cpProjectJourney={reset};reset();
 }
 if(!reduced&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');observer.unobserve(e.target);}}),{threshold:.07});root.querySelectorAll('.section-head,.service-list article,.studio-grid,.process article').forEach(x=>{x.classList.add('reveal');observer.observe(x);});}
 const progress=root.querySelector('.read-progress');let scheduled=false;function scroll(){progress.style.transform=`scaleX(${scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)})`;scheduled=false;}addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(scroll);}},{passive:true});scroll();root.querySelector('#year').textContent=new Date().getFullYear();
 window.cpDevInitScene=function(){
  const canvas=root.querySelector('#dev-canvas');if(canvas.dataset.ready||!window.THREE)return;
  const T=window.THREE;let renderer;try{renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true,preserveDrawingBuffer:true});}catch(e){return;}canvas.dataset.ready='true';root.querySelector('.scene').classList.add('ready');
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,100);camera.position.set(0,.6,10);camera.lookAt(0,0,0);
  scene.add(new T.AmbientLight(0xa89abb,.8));const key=new T.DirectionalLight(0xf6e4ff,2.5);key.position.set(3,5,4);scene.add(key);const rim=new T.PointLight(0xa54fea,4,22);rim.position.set(2,2,-2);scene.add(rim);const fill=new T.PointLight(0x8df4db,2,20);fill.position.set(-3,-1,4);scene.add(fill);
  const metal=new T.MeshStandardMaterial({color:0x2e2739,metalness:.9,roughness:.24}),edge=new T.MeshStandardMaterial({color:0x9c69c6,metalness:.7,roughness:.3}),black=new T.MeshStandardMaterial({color:0x08070d,metalness:.4,roughness:.25});
  function box(w,h,d,mat,x=0,y=0,z=0){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);return m;}
  const devices=new T.Group();scene.add(devices);
  function texture(mobile){const c=document.createElement('canvas');c.width=mobile?480:1280;c.height=mobile?900:800;const ctx=c.getContext('2d');ctx.fillStyle='#12101a';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#a78abf';ctx.font=mobile?'18px Arial':'24px Arial';ctx.fillText('CHISHTY / DIGITAL STUDIO',mobile?25:55,mobile?52:68);ctx.strokeStyle='#43364e';ctx.beginPath();ctx.moveTo(25,mobile?78:98);ctx.lineTo(c.width-25,mobile?78:98);ctx.stroke();ctx.fillStyle='#f5ecff';ctx.font=mobile?'bold 54px Arial':'bold 90px Arial';ctx.fillText('Build beyond',mobile?25:55,mobile?164:228);ctx.fillText('the ordinary.',mobile?25:55,mobile?226:329);ctx.fillStyle='#ba80e6';ctx.fillRect(mobile?25:55,mobile?266:378,mobile?235:285,mobile?48:60);ctx.fillStyle='#170e20';ctx.font=mobile?'20px Arial':'26px Arial';ctx.fillText('Explore the work',mobile?45:83,mobile?297:417);ctx.fillStyle='#a1d8c6';ctx.font=mobile?'18px Arial':'22px Arial';ctx.fillText('WEB / MOBILE / INTERACTIVE',mobile?25:55,mobile?362:510);const top=mobile?408:555;for(let i=0;i<3;i++){ctx.fillStyle=['#31243e','#1f3434','#292530'][i];ctx.fillRect(mobile?25:55+i*405,mobile?top+i*134:top,mobile?430:365,mobile?110:185);ctx.fillStyle=['#b978e7','#a4ddcb','#f2c879'][i];ctx.font=mobile?'36px Arial':'42px Arial';ctx.fillText(['</>','{ }','01'][i],mobile?50:78+i*405,mobile?top+67+i*134:top+88);ctx.fillStyle='#d0c4dc';ctx.font='18px Arial';ctx.fillText(['Web development','Mobile applications','Digital experiences'][i],mobile?135:78+i*405,mobile?top+65+i*134:top+142);}const tex=new T.CanvasTexture(c);tex.encoding=T.sRGBEncoding;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();return tex;}
  const laptop=new T.Group();laptop.add(box(3.5,2.35,.12,metal,0,.28,0));laptop.add(box(3.56,2.41,.065,edge,0,.28,-.075));const laptopScreen=new T.Mesh(new T.PlaneGeometry(3.27,2.07),new T.MeshBasicMaterial({map:texture(false)}));laptopScreen.position.set(0,.3,.067);laptop.add(laptopScreen);laptop.add(box(3.8,.11,2.2,metal,0,-.96,.86));laptop.add(box(3.83,.025,2.21,edge,0,-1.025,.86));for(let row=0;row<4;row++)for(let col=0;col<12;col++){const k=box(.23,.023,.17,black,-1.51+col*.275,-.893,.3+row*.23);laptop.add(k);}laptop.add(box(1.02,.017,.52,black,0,-.89,1.55));laptop.rotation.set(-.09,-.46,-.05);devices.add(laptop);
  const phone=new T.Group();phone.add(box(.95,1.92,.15,metal));phone.add(box(1,1.96,.1,edge,0,0,-.035));const phoneScreen=new T.Mesh(new T.PlaneGeometry(.83,1.69),new T.MeshBasicMaterial({map:texture(true)}));phoneScreen.position.set(0,.01,.08);phone.add(phoneScreen);phone.add(box(.26,.045,.012,black,0,.84,.086));phone.position.set(1.8,-.34,1.15);phone.rotation.set(.03,-.24,.11);devices.add(phone);
  const ringMat=new T.MeshStandardMaterial({color:0xa66bcc,metalness:.9,roughness:.19});const arc=new T.Mesh(new T.TorusGeometry(2.65,.015,8,150),ringMat);arc.rotation.set(1.07,.25,.1);arc.position.set(0,-.28,-.9);devices.add(arc);const arc2=new T.Mesh(new T.TorusGeometry(2.8,.009,8,150),new T.MeshBasicMaterial({color:0x81998e,transparent:true,opacity:.33}));arc2.rotation.set(.2,.65,.2);arc2.position.set(0,-.1,-1.5);devices.add(arc2);
  const waterMaterial=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{uTime:{value:0},uPurple:{value:new T.Color('#ad72ce')},uMint:{value:new T.Color('#81bdae')}},vertexShader:`uniform float uTime; varying vec3 vWorld; varying float vWave;
   void main(){vec3 p=position;float wave=sin(p.x*.75+uTime*.48)*.16+cos(p.y*.86-uTime*.36)*.13+sin(p.x*.4+p.y*.62+uTime*.3)*.12;p.z+=wave;vWave=wave;vec4 world=modelMatrix*vec4(p,1.);vWorld=world.xyz;gl_Position=projectionMatrix*viewMatrix*world;}`,fragmentShader:`uniform float uTime;uniform vec3 uPurple;uniform vec3 uMint;varying vec3 vWorld;varying float vWave;
   void main(){float ripple=sin(vWorld.x*2.4+vWorld.z*1.5+uTime*.45+vWave*5.);float crest=pow(max(0.,ripple),10.);float sheen=pow(max(0.,sin(vWorld.x*.5-vWorld.z*.62+uTime*.12)),4.);float fade=1.-smoothstep(3.,13.,length(vWorld.xz));vec3 color=mix(uPurple,uMint,smoothstep(-.2,.3,vWave));color=mix(vec3(.035,.025,.06),color,crest*.55+sheen*.16);gl_FragColor=vec4(color,fade*.82);}`});
  const water=new T.Mesh(new T.PlaneGeometry(30,24,100,75),waterMaterial);water.rotation.x=-Math.PI/2;water.position.set(0,-2.05,-2);scene.add(water);canvas.dataset.water='flowing';
  let targetX=0,targetY=0,visible=true,inspecting=false,paused=reduced,dragging=false,dragX=0,dragY=0,yaw=0,pitch=0,inspectBlend=0,scrollBlend=0;
  const hero=root.querySelector('.hero'),tools=root.querySelector('.scene-tools'),inspectButton=root.querySelector('#scene-inspect'),motionButton=root.querySelector('#scene-motion');tools.hidden=false;
  function motionState(){motionButton.setAttribute('aria-pressed',String(paused));motionButton.setAttribute('aria-label',paused?'Resume water and model animation':'Pause water and model animation');motionButton.title=paused?'Resume animation':'Pause animation';motionButton.innerHTML='<i data-lucide="'+(paused?'play':'pause')+'"></i>';icons();}motionState();motionButton.addEventListener('click',()=>{paused=!paused;motionState();});
  function inspect(value){inspecting=value;hero.classList.toggle('inspecting',value);inspectButton.setAttribute('aria-pressed',String(value));inspectButton.setAttribute('aria-label',value?'Return to portfolio':'Inspect 3D models');inspectButton.title=value?'Return to portfolio':'Inspect 3D models';inspectButton.innerHTML='<i data-lucide="'+(value?'minimize-2':'maximize-2')+'"></i>';icons();if(!value){yaw=pitch=0;}else canvas.focus({preventScroll:true});}
  inspectButton.addEventListener('click',()=>inspect(!inspecting));root.querySelector('#scene-reset').addEventListener('click',()=>{yaw=pitch=targetX=targetY=0;});
  hero.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||dragging||inspecting)return;const r=hero.getBoundingClientRect();targetX=(e.clientX-r.left)/r.width-.5;targetY=(e.clientY-r.top)/r.height-.5;});hero.addEventListener('pointerleave',()=>{targetX=targetY=0;});
  canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!inspecting)return;dragging=true;dragX=e.clientX;dragY=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw+=(e.clientX-dragX)*.008;pitch=Math.max(-.4,Math.min(.4,pitch+(e.clientY-dragY)*.005));dragX=e.clientX;dragY=e.clientY;canvas.dataset.rotation=yaw.toFixed(2);});function release(){dragging=false;}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
  canvas.addEventListener('keydown',e=>{if(e.key==='Escape'){inspect(false);inspectButton.focus();return;}if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.18;if(e.key==='ArrowRight')yaw+=.18;if(e.key==='ArrowUp')pitch=Math.max(-.4,pitch-.1);if(e.key==='ArrowDown')pitch=Math.min(.4,pitch+.1);canvas.dataset.rotation=yaw.toFixed(2);});
  let mobile=false;function resize(){const r=hero.getBoundingClientRect();mobile=r.width<760;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();devices.position.set(mobile?-.08:2.2,mobile?-1.45:-.06,0);devices.scale.setScalar(mobile?.54:.86);laptop.rotation.y=mobile?-.23:-.46;phone.position.x=mobile?1.55:1.8;camera.position.z=mobile?10.5:10;}
  new ResizeObserver(resize).observe(hero);resize();if('IntersectionObserver'in window)new IntersectionObserver(e=>{visible=e[0].isIntersecting;},{threshold:0}).observe(hero);
  const clock=new T.Clock();let waterTime=0;function frame(){requestAnimationFrame(frame);const delta=Math.min(clock.getDelta(),.05);if(!visible||document.hidden)return;if(!paused)waterTime+=delta;waterMaterial.uniforms.uTime.value=waterTime;
   const r=hero.getBoundingClientRect(),scrollTarget=reduced?0:Math.max(0,Math.min(1,-r.top/r.height));scrollBlend+=(scrollTarget-scrollBlend)*.055;inspectBlend+=(Number(inspecting)-inspectBlend)*(reduced?1:.06);
   devices.position.x=(mobile?-.08:2.2)*(1-inspectBlend);devices.position.y=(mobile?-1.45:-.06)*(1-inspectBlend)+scrollBlend*.3;devices.scale.setScalar((mobile?.54:.86)+inspectBlend*(mobile?.1:.16));camera.position.z=(mobile?10.5:10)-inspectBlend*(mobile?.4:1.1)-scrollBlend*.35;
   devices.rotation.y+=((paused?0:targetX*.2)+yaw+scrollBlend*.22-devices.rotation.y)*.06;devices.rotation.x+=((paused?0:-targetY*.1)+pitch-scrollBlend*.05-devices.rotation.x)*.06;
   laptop.position.y=Math.sin(waterTime*.55)*.065;laptop.rotation.z=-.05+Math.sin(waterTime*.35)*.018;phone.position.y=-.34+Math.sin(waterTime*.7+1)*.09;arc.rotation.z=waterTime*.025;renderer.render(scene,camera);
  }frame();
 };
 window.cpDevInitScene();
})();
