'use strict';
const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const reduced = matchMedia('(prefers-reduced-motion: reduce)');
let motionPaused = reduced.matches;
const menu = $('.menu-toggle');
menu.addEventListener('click', () => {const open = menu.getAttribute('aria-expanded') !== 'true';menu.setAttribute('aria-expanded', String(open));menu.setAttribute('aria-label', open ? 'Close navigation' : 'Open navigation');$('#mobile-nav').hidden = !open;});
$$('#mobile-nav a').forEach(a => a.addEventListener('click', () => {menu.setAttribute('aria-expanded', 'false');menu.setAttribute('aria-label','Open navigation');$('#mobile-nav').hidden = true;}));
const motionButton = $('#motion-toggle');
function setMotion(){motionButton.textContent=motionPaused?'Resume motion':'Pause motion';motionButton.setAttribute('aria-pressed',String(motionPaused));document.body.classList.toggle('motion-paused',motionPaused);document.dispatchEvent(new CustomEvent('cp-motion',{detail:motionPaused}));}
motionButton.addEventListener('click',()=>{motionPaused=!motionPaused;setMotion();});setMotion();
reduced.addEventListener('change',()=>{motionPaused=reduced.matches;setMotion();});
$('#year').textContent=new Date().getFullYear();
const canvas=$('#grid-canvas'),ctx=canvas.getContext('2d');let cw=0,ch=0,pointer={x:0,y:0},t=0,frame=0;
function resizeGrid(){const r=canvas.getBoundingClientRect();cw=r.width;ch=r.height;const d=Math.min(devicePixelRatio,1.5);canvas.width=cw*d;canvas.height=ch*d;ctx.setTransform(d,0,0,d,0,0);}
new ResizeObserver(resizeGrid).observe(canvas);
$('.hero').addEventListener('pointermove',e=>{if(motionPaused||e.pointerType==='touch')return;const r=canvas.getBoundingClientRect();pointer={x:(e.clientX-r.left)/r.width-.5,y:(e.clientY-r.top)/r.height-.5};});
$('.hero').addEventListener('pointerleave',()=>{pointer={x:0,y:0};});
function drawGrid(){requestAnimationFrame(drawGrid);if(document.hidden)return;frame++;if(frame%2)return;const visible=canvas.getBoundingClientRect().bottom>0;if(!visible)return;if(!motionPaused)t+=.003;ctx.clearRect(0,0,cw,ch);ctx.strokeStyle='#876299';ctx.lineWidth=.5;ctx.globalAlpha=.14;const step=90;const offset=motionPaused?0:Math.sin(t)*8;for(let x=-step;x<cw+step;x+=step){ctx.beginPath();ctx.moveTo(x+offset,0);ctx.lineTo(x+offset,ch);ctx.stroke();}for(let y=-step;y<ch+step;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(cw,y);ctx.stroke();}ctx.globalAlpha=.55;ctx.fillStyle='#a785bc';for(let x=40;x<cw;x+=180)for(let y=45;y<ch;y+=180){ctx.fillRect(x+offset,y,2,2);}}
drawGrid();let scrollQueued=false;function updateScroll(){$('.read-progress').style.transform=`scaleX(${scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)})`;scrollQueued=false;}addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(updateScroll);}},{passive:true});updateScroll();

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const projects=window.CP_PROJECTS||[];
const grid=$('#project-grid');
grid.innerHTML=projects.map((p,i)=>`<article class="project-card reveal" data-project-id="${p.id}" data-category="${p.category.join(' ')}"><div class="project-visual">${p.image?`<img src="${p.image}" alt="${esc(p.alt||p.title+' video thumbnail')}" loading="lazy" width="1000" height="588">`:`<div class="video-poster"><p>${esc(p.title)}</p><span>CHISHTY PRODUCTIONS / PROJECT STUDY</span></div>`}<span class="project-tag">${p.video?'VIDEO EDIT':p.id==='portfolio'?'BRAND WEBSITE':p.coverArtwork?'PROJECT ARTWORK':p.category.includes('mobile')?'WEB + MOBILE':'INTERACTIVE'}</span><button class="project-open" data-project="${p.id}" aria-label="${p.video?'Watch':'Explore'} ${esc(p.title)}">${p.video?'▷':'+'}</button></div><div class="project-meta"><h3>${esc(p.title)}</h3><span>${String(i+1).padStart(2,'0')} / ${p.video?'VIDEO':'BUILD'}</span></div><p>${esc(p.description)}</p><div class="tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></article>`).join('');
$$('.project-visual img').forEach(img=>img.addEventListener('error',()=>{const p=projects.find(p=>p.image===img.getAttribute('src'));const fallback=document.createElement('div');fallback.className='video-poster';fallback.innerHTML=`<p>${esc(p.title)}</p><span>${p.video?'SELECTED VIDEO EDIT':'PROJECT PREVIEW'}</span>`;img.replaceWith(fallback);},{once:true}));
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{let count=0;$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('.project-card').forEach(c=>{c.hidden=b.dataset.filter!=='all'&&!c.dataset.category.split(' ').includes(b.dataset.filter);c.classList.toggle('filtered',b.dataset.filter!=='all');c.classList.add('visible');if(!c.hidden)count++;});$('.work-count').textContent=`${count} project${count===1?'':'s'}`;$('.video-filters').hidden=b.dataset.filter!=='video';$$('[data-video-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.videoFilter==='all')));resetJourney();}));

const serviceTabs=$$('[role=tab]');
function selectService(tab){serviceTabs.forEach(b=>{const on=b===tab;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;$('#'+b.getAttribute('aria-controls')).hidden=!on;});}
serviceTabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectService(tab));tab.addEventListener('keydown',e=>{let target;if(e.key==='ArrowRight'||e.key==='ArrowDown')target=(i+1)%3;if(e.key==='ArrowLeft'||e.key==='ArrowUp')target=(i+2)%3;if(e.key==='Home')target=0;if(e.key==='End')target=2;if(target!==undefined){e.preventDefault();selectService(serviceTabs[target]);serviceTabs[target].focus();}});});

const projectDialog=$('#project-dialog');
let lastDialogTrigger=null;
function openDialog(dialog,trigger){lastDialogTrigger=trigger;dialog.showModal();document.body.classList.add('modal-open');}
$$('.dialog-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$$('dialog').forEach(d=>{d.addEventListener('close',()=>{document.body.classList.remove('modal-open');const frame=$('iframe',d);if(frame)frame.removeAttribute('src');if(lastDialogTrigger)lastDialogTrigger.focus({preventScroll:true});});d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();});});
$$('[data-project]').forEach(b=>b.addEventListener('click',()=>{const p=projects.find(p=>p.id===b.dataset.project);const target=$('#project-details');target.innerHTML=`<p class="eyebrow">${esc(p.label)}</p><h2 id="project-title">${esc(p.title)}</h2>${p.video?`<iframe class="video-frame" title="${esc(p.title)} video" src="https://drive.google.com/file/d/${p.video}/preview" allow="autoplay; fullscreen" allowfullscreen></iframe><p class="video-help">${esc(p.description)}<br>If the embedded player needs access, open the original video.</p><div class="project-links"><a class="button primary" href="https://drive.google.com/file/d/${p.video}/view" target="_blank" rel="noopener noreferrer">Open original video</a></div>`:`${p.image?`<img src="${p.image}" alt="${esc(p.alt||p.title)}">`:`<div class="project-source-panel"><strong>${esc(p.title)}</strong><span>PUBLIC SOURCE / ${esc(p.tags.join(' · '))}</span></div>`}<p>${esc(p.detail)}</p><ul>${p.features.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="project-links">${p.live?`<a class="button primary" href="${p.live}" target="_blank" rel="noopener noreferrer">Visit live project</a>`:''}<a class="button" href="https://github.com/Adil-Amin-Chishty/${p.repo}" target="_blank" rel="noopener noreferrer">View source</a></div>`}`;openDialog(projectDialog,b);}));

const briefDialog=$('#brief-dialog'),form=$('#brief-form');let briefText='';
$$('.brief-trigger').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.choice)form.elements.service.value=b.dataset.choice;form.hidden=false;$('#brief-result').hidden=true;$('#brief-send-status').textContent='';window.CPEnquiry.updateForm(form,briefDialog,$('#prepare-email'),'project');openDialog(briefDialog,b);}));
function prepareBrief(){if(!form.reportValidity())return null;const data=new FormData(form);const payload={kind:'project',name:String(data.get('name')).trim(),email:String(data.get('email')).trim(),service:data.get('service'),budget:data.get('budget'),idea:String(data.get('idea')).trim(),website:String(data.get('website')||'')};briefText='PROJECT ENQUIRY — CHISHTY PRODUCTIONS\n\nName: '+payload.name+'\nEmail: '+payload.email+'\nService: '+payload.service+'\nBudget (USD): '+payload.budget+'\n\nThe idea:\n'+payload.idea;$('#brief-preview').textContent=briefText;$('#send-email').href='mailto:chishtyproduction001@gmail.com?subject='+encodeURIComponent(payload.service+' enquiry — '+payload.name)+'&body='+encodeURIComponent(briefText);return payload;}
function briefResult(sent){form.hidden=true;$('#brief-result').hidden=false;$('#brief-result h3').textContent=sent?'Enquiry received.':'Your email draft is ready.';$('#send-email').hidden=!!sent;$('#brief-status').textContent=sent?'Reference: '+sent.reference:'';$('.brief-note',briefDialog).textContent=sent?(sent.acknowledgementSent?'A confirmation email has been sent to your email address. We’ll contact you shortly.':'Your enquiry reached our studio. We’ll contact you shortly.'):'This opens your email app. Review the draft and press Send there.';(sent?$('#copy-brief'):$('#send-email')).focus();}
form.addEventListener('submit',async e=>{e.preventDefault();const payload=prepareBrief();if(!payload)return;const button=$('button[type=submit]',form),status=$('#brief-send-status');button.disabled=true;button.textContent='Sending…';status.textContent='';try{const sent=await window.CPEnquiry.send(payload);briefResult(sent);}catch(error){status.textContent=error.message;}finally{button.disabled=false;button.textContent='Send enquiry ↗';}});
$('#prepare-email').addEventListener('click',()=>{if(prepareBrief())briefResult(null);});
$('#edit-brief').addEventListener('click',()=>{form.hidden=false;$('#brief-result').hidden=true;form.elements.idea.focus();});
$('#copy-brief').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(briefText);$('#brief-status').textContent='Brief copied. Paste it into your email or Instagram message.';}catch{$('#brief-status').textContent='Select the brief text above to copy it, or download it below.';const range=document.createRange();range.selectNodeContents($('#brief-preview'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);}});
$('#download-brief').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([briefText],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='chishty-project-brief.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#brief-status').textContent='Your brief is ready to download.';});
if('IntersectionObserver'in window&&!reduced.matches){document.body.classList.add('has-observer');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});$$('.reveal').forEach(el=>observer.observe(el));}
const backTop=$('#back-top');addEventListener('scroll',()=>{backTop.hidden=scrollY<700;},{passive:true});backTop.addEventListener('click',()=>scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'}));
if(matchMedia('(pointer:fine)').matches)$$('.project-card,.studio-card').forEach(c=>c.addEventListener('pointermove',e=>{if(motionPaused)return;const r=c.getBoundingClientRect();c.style.setProperty('--mx',(e.clientX-r.left)/r.width*100+'%');c.style.setProperty('--my',(e.clientY-r.top)/r.height*100+'%');}));
$$('[data-video-filter]').forEach(b=>b.addEventListener('click',()=>{let count=0;$$('[data-video-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('.project-card').forEach(c=>{const cats=c.dataset.category.split(' ');c.hidden=!cats.includes('video')||(b.dataset.videoFilter!=='all'&&!cats.includes(b.dataset.videoFilter));c.classList.add('visible');if(!c.hidden)count++;});$('.work-count').textContent=`${count} project${count===1?'':'s'}`;resetJourney();}));
let immersive=false,shownCards=[],journeyFrame=false;
const journey=$('#project-journey'),rail=$('#journey-rail'),viewToggle=$('#view-toggle');
function journeyUnit(){return Math.max(500,innerHeight-110)*.8;}
function drawJourney(){journeyFrame=false;if(!immersive)return;const pos=Math.max(0,Math.min(shownCards.length-1,(-journey.getBoundingClientRect().top+100)/journeyUnit()));const current=Math.round(pos);shownCards.forEach((card,i)=>{const d=i-pos;card.style.transform=`translate3d(${d*70}px,${Math.abs(d)*25}px,${-Math.abs(d)*650}px) rotateY(${-d*8}deg)`;card.style.opacity=String(Math.max(0,1-Math.abs(d)*1.1));card.style.zIndex=String(20-Math.abs(Math.round(d*5)));card.style.pointerEvents=i===current?'auto':'none';card.inert=i!==current;card.setAttribute('aria-hidden',String(i!==current));});$$('button',rail).forEach((b,i)=>b.setAttribute('aria-current',i===current?'step':'false'));}
function queueJourney(){if(immersive&&!journeyFrame){journeyFrame=true;requestAnimationFrame(drawJourney);}}
function resetJourney(){shownCards=$$('.project-card').filter(c=>!c.hidden);journey.style.height=immersive?`${Math.max(500,innerHeight-110)+(shownCards.length-1)*journeyUnit()}px`:'';rail.hidden=!immersive;if(immersive){rail.innerHTML=shownCards.map((c,i)=>`<button aria-label="Go to ${esc($('h3',c).textContent)}" title="${esc($('h3',c).textContent)}">${String(i+1).padStart(2,'0')}</button>`).join('');$$('button',rail).forEach((b,i)=>b.addEventListener('click',()=>scrollTo({top:journey.getBoundingClientRect().top+scrollY+i*journeyUnit()-100,behavior:motionPaused?'instant':'smooth'})));drawJourney();}else{$$('.project-card').forEach(c=>{['transform','opacity','z-index','pointer-events'].forEach(p=>c.style.removeProperty(p));c.inert=false;c.removeAttribute('aria-hidden');});}}
viewToggle.addEventListener('click',()=>{immersive=!immersive;journey.classList.toggle('depth-mode',immersive);viewToggle.setAttribute('aria-pressed',String(immersive));viewToggle.textContent=immersive?'Grid view':'Immersive view';resetJourney();if(immersive)journey.scrollIntoView({block:'start',behavior:'instant'});});
addEventListener('scroll',queueJourney,{passive:true});addEventListener('resize',()=>{if(immersive)resetJourney();});

const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();const tool={name:'stage_project_brief',title:'Prepare a project brief',description:'Open the project enquiry composer and fill its visible fields. This stages a draft; it does not send or submit an enquiry.',inputSchema:{type:'object',properties:{name:{type:'string',maxLength:100},email:{type:'string',maxLength:200},service:{type:'string',enum:['Web development','Mobile app development','Video editing','A combination of services']},idea:{type:'string',maxLength:4000}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||!['Web development','Mobile app development','Video editing','A combination of services'].includes(input.service))throw Error('Choose a supported service.');for(const k of Object.keys(input))if(!['name','email','service','idea'].includes(k)||typeof input[k]!=='string')throw Error('Invalid brief field.');if((input.name?.length||0)>100||(input.email?.length||0)>200||(input.idea?.length||0)>4000)throw Error('Brief field exceeds the supported length.');form.hidden=false;$('#brief-result').hidden=true;for(const k of ['name','email','service','idea'])if(input[k]!==undefined)form.elements[k].value=input[k];window.CPEnquiry.updateForm(form,briefDialog,$('#prepare-email'),'project');if(!briefDialog.open)openDialog(briefDialog,$('.brief-trigger'));return{status:'draft_staged',service:form.elements.service.value,sent:false};}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

