(()=>{'use strict';const q=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];const grid=q('#project-grid');grid.classList.add('tree-grid');const intro=document.createElement('div');intro.className='tree-intro';intro.innerHTML='<span class="tree-root" aria-hidden="true">CP</span><span>ONE STUDIO. MANY POSSIBILITIES.</span>';q('#journey-stage').before(intro);
const heading=q('#services h2');let word=0;heading.innerHTML=heading.innerHTML.replace(/Three disciplines\./,'<span class="cap-word" style="--word:0">Three</span> <span class="cap-word" style="--word:1">disciplines.</span>');
let queued=false;function drawTree(){queued=false;const r=grid.getBoundingClientRect();const fill=Math.max(0,Math.min(100,(innerHeight*.72-r.top)/Math.max(1,r.height)*100));grid.style.setProperty('--tree-fill',fill+'%');}addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(drawTree);}},{passive:true});drawTree();all('[data-filter],[data-video-filter]').forEach(b=>b.addEventListener('click',()=>{all('.project-card:not([hidden])').forEach((c,i)=>{c.style.gridColumn=i%2?'2':'1';if(innerWidth<=760||q('#project-journey').classList.contains('depth-mode'))c.style.gridColumn='';});drawTree();}));addEventListener('resize',()=>all('.project-card').forEach(c=>c.style.gridColumn=''));
const dialog=q('#booking-dialog'),form=q('#booking-form'),result=q('#booking-result'),zone=Intl.DateTimeFormat().resolvedOptions().timeZone;let requestText='';q('#booking-zone').textContent='Times are shown in your time zone: '+zone;function localDate(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}form.elements.date.min=localDate(new Date());all('.booking-trigger').forEach(b=>b.addEventListener('click',()=>{form.hidden=false;result.hidden=true;q('#booking-send-status').textContent='';form.elements.date.min=localDate(new Date());window.CPEnquiry.updateForm(form,dialog,q('#prepare-call-email'),'call');openDialog(dialog,b);form.elements.name.focus();}));
function prepareCall(){if(!form.reportValidity())return null;const d=new Date(form.elements.date.value+'T'+form.elements.time.value),end=new Date(d.getTime()+30*60000);if(d<=new Date()){form.elements.date.setCustomValidity('Choose a future date and time.');form.elements.date.reportValidity();return null;}const name=form.elements.name.value.trim(),email=form.elements.email.value.trim(),idea=form.elements.idea.value.trim();requestText='DISCOVERY CALL REQUEST — CHISHTY PRODUCTIONS\n\nName: '+name+'\nEmail: '+email+'\nProposed time: '+d.toLocaleString()+' ('+zone+')\nUTC: '+d.toISOString()+'\nDuration: 30 minutes\n\nProject: '+idea+'\n\nPlease confirm availability and share the meeting link.';q('#booking-email').href='mailto:chishtyproduction001@gmail.com?subject='+encodeURIComponent('Discovery call request — '+name)+'&body='+encodeURIComponent(requestText);const stamp=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');q('#booking-calendar').href='https://calendar.google.com/calendar/render?'+new URLSearchParams({action:'TEMPLATE',text:'Proposed call — Chishty Productions',dates:stamp(d)+'/'+stamp(end),details:'Proposed time — awaiting studio confirmation.\n\n'+idea,location:'Remote — meeting link after confirmation'});q('#booking-summary').textContent=d.toLocaleString()+' · '+zone+' · 30 minutes';return{kind:'call',name,email,idea,service:'A combination of services',budget:'Let’s discuss',proposedTime:d.toISOString(),timezone:zone,website:form.elements.website.value};}
function callResult(sent){form.hidden=true;result.hidden=false;q('#booking-result h3').textContent=sent?'Call request received.':'Your proposed time is ready.';q('#booking-email').hidden=!!sent;q('#booking-status').textContent=sent?'Reference: '+sent.reference:'';q('#booking-result .brief-note').textContent=sent?'Your call request has reached our studio. We’ll confirm availability and share the meeting link by email.'+(sent.acknowledgementSent?' A confirmation email has been sent.':''):'Send the email request to the studio. The Calendar link creates a draft in your calendar; this time is confirmed after our reply.';(sent?q('#booking-calendar'):q('#booking-email')).focus();}
form.addEventListener('submit',async e=>{e.preventDefault();const payload=prepareCall();if(!payload)return;const button=q('#booking-form button[type=submit]'),status=q('#booking-send-status');button.disabled=true;button.textContent='Sending…';status.textContent='';try{callResult(await window.CPEnquiry.send(payload));}catch(error){status.textContent=error.message;}finally{button.disabled=false;button.textContent='Send call request ↗';}});q('#prepare-call-email').onclick=()=>{if(prepareCall())callResult(null);};
form.elements.date.addEventListener('input',()=>form.elements.date.setCustomValidity(''));form.elements.time.addEventListener('input',()=>form.elements.date.setCustomValidity(''));q('#booking-edit').onclick=()=>{form.hidden=false;result.hidden=true;form.elements.date.focus();};q('#booking-copy').onclick=async()=>{try{await navigator.clipboard.writeText(requestText);q('#booking-status').textContent='Call request copied.';}catch{q('#booking-status').textContent=requestText;}};
})();

