(()=>{'use strict';
const q=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const hero=q('.future-hero'),viewport=document.createElement('div');viewport.className='portal-viewport';while(hero.firstChild)viewport.append(hero.firstChild);hero.append(viewport);
const slides=[{title:'WE BUILD<br><span class="outlined">WHAT\'S</span><br><em>NEXT.</em>',description:'Distinctive websites. Intuitive apps.<br>Scroll to step inside.'},{title:'STEP<br><span class="outlined">INSIDE</span><br><em>THE IDEA.</em>',description:'Every screen. Every interaction.<br>A world built around your vision.'},{title:'BEYOND<br><span class="outlined">THE</span><br><em>ORDINARY.</em>',description:'Web. Mobile. Film.<br>Welcome to Chishty Productions.'}];
let stage=-1,ticking=false;const keys=['web','mobile','video'],reduced=matchMedia('(prefers-reduced-motion: reduce)');
function update(){ticking=false;const p=Math.max(0,Math.min(1,-hero.getBoundingClientRect().top/Math.max(1,hero.offsetHeight-innerHeight)));const disabled=reduced.matches||document.body.classList.contains('motion-paused');const next=disabled?0:Math.min(2,Math.floor(p*3));if(next!==stage){stage=next;q('#hero-title').innerHTML=slides[next].title;q('#hero-description').innerHTML=slides[next].description;all('.hero-slide').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===next)));}hero.style.setProperty('--portal-scale',disabled?1:1+p*p*2.8);hero.style.setProperty('--portal-progress',p);hero.style.setProperty('--copy-depth',disabled?'0px':(-p*55)+'px');hero.style.setProperty('--copy-opacity',disabled?1:p>.9?1-(p-.9)*7:1);}
function schedule(){if(!ticking){ticking=true;requestAnimationFrame(update);}}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);document.addEventListener('cp-motion',schedule);reduced.addEventListener('change',schedule);update();
all('.hero-slide').forEach((b,i)=>b.addEventListener('click',()=>{if(reduced.matches||document.body.classList.contains('motion-paused'))return;scrollTo({top:hero.offsetTop+(hero.offsetHeight-innerHeight)*(i/3+.02),behavior:'smooth'});}));
all('[data-map-service]').forEach(b=>b.addEventListener('click',()=>{q('#tab-'+b.dataset.mapService).click();q('#services').scrollIntoView({behavior:reduced.matches?'instant':'smooth'});}));
all('[data-studio-mode]').forEach(b=>b.addEventListener('click',()=>{const film=b.dataset.studioMode==='film';all('[data-studio-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));q('#tab-'+(film?'video':'web')).click();q('[data-filter="'+(film?'video':'all')+'"]').click();}));
const projects=window.CP_PROJECTS;function open(id){q('.project-open[data-project="'+id+'"]').click();}
const featured=['asa','shop','heads'];let feature=0;function showFeature(){const p=projects.find(x=>x.id===featured[feature]);q('#feature-image').src=p.image;q('#feature-image').alt=p.alt;q('#feature-index').textContent='0'+(feature+1)+' / 03';q('#feature-title').textContent=p.title;q('#feature-type').textContent=p.label;q('#feature-description').textContent=p.description;}q('#feature-prev').onclick=()=>{feature=(feature+2)%3;showFeature();};q('#feature-next').onclick=()=>{feature=(feature+1)%3;showFeature();};q('.feature-open').onclick=()=>open(featured[feature]);
let film='video-journey';all('[data-cinema]').forEach((b,i)=>b.addEventListener('click',()=>{film=b.dataset.cinema;const p=projects.find(x=>x.id===film),img=q('#cinema-poster');img.hidden=!p.image;if(p.image){img.src=p.image;img.alt=p.title+' — video sample';}q('.cinema-stage').classList.toggle('posterless',!p.image);q('#cinema-title').textContent=p.title;q('.cinema-time').textContent='SELECTED VIDEO / 0'+(i+1);all('[data-cinema]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));q('#cinema-play').onclick=()=>open(film);
if(matchMedia('(pointer:fine)').matches&&!reduced.matches){const cursor=document.createElement('div');cursor.className='cursor-orbit';cursor.setAttribute('aria-hidden','true');document.body.append(cursor);addEventListener('pointermove',e=>{cursor.style.transform=`translate(${e.clientX-19}px,${e.clientY-19}px)`;cursor.classList.toggle('active',!!e.target.closest('a,button,.project-visual'));},{passive:true});}
})();
