(()=>{const root=document;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function icons(){}
window.cpDevInitScene=function(){
  const canvas=root.querySelector('#dev-canvas');if(canvas.dataset.ready||!window.THREE)return;
  const T=window.THREE;let renderer;try{renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true,preserveDrawingBuffer:true});}catch(e){return;}canvas.dataset.ready='true';root.querySelector('.scene').classList.add('ready');
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,100);camera.position.set(0,.6,10);camera.lookAt(0,0,0);
  scene.add(new T.AmbientLight(0xa89abb,.8));const key=new T.DirectionalLight(0xf6e4ff,2.5);key.position.set(3,5,4);scene.add(key);const rim=new T.PointLight(0xa54fea,4,22);rim.position.set(2,2,-2);scene.add(rim);const fill=new T.PointLight(0x8df4db,2,20);fill.position.set(-3,-1,4);scene.add(fill);
  const metal=new T.MeshStandardMaterial({color:0x2e2739,metalness:.9,roughness:.24}),edge=new T.MeshStandardMaterial({color:0x9c69c6,metalness:.7,roughness:.3}),black=new T.MeshStandardMaterial({color:0x08070d,metalness:.4,roughness:.25});
  function box(w,h,d,mat,x=0,y=0,z=0){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);return m;}
  const devices=new T.Group();scene.add(devices);
  function texture(mobile){const c=document.createElement('canvas');c.width=mobile?480:1280;c.height=mobile?900:800;const ctx=c.getContext('2d');ctx.fillStyle='#12101a';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#a78abf';ctx.font=mobile?'18px Arial':'24px Arial';ctx.fillText('CHISHTY / DIGITAL STUDIO',mobile?25:55,mobile?52:68);ctx.strokeStyle='#43364e';ctx.beginPath();ctx.moveTo(25,mobile?78:98);ctx.lineTo(c.width-25,mobile?78:98);ctx.stroke();ctx.fillStyle='#f5ecff';ctx.font=mobile?'bold 54px Arial':'bold 90px Arial';ctx.fillText('Build beyond',mobile?25:55,mobile?164:228);ctx.fillText('the ordinary.',mobile?25:55,mobile?226:329);ctx.fillStyle='#ba80e6';ctx.fillRect(mobile?25:55,mobile?266:378,mobile?235:285,mobile?48:60);ctx.fillStyle='#170e20';ctx.font=mobile?'20px Arial':'26px Arial';ctx.fillText('Explore the work',mobile?45:83,mobile?297:417);ctx.fillStyle='#a1d8c6';ctx.font=mobile?'18px Arial':'22px Arial';ctx.fillText('WEB / MOBILE / INTERACTIVE',mobile?25:55,mobile?362:510);const top=mobile?408:555;for(let i=0;i<3;i++){ctx.fillStyle=['#31243e','#1f3434','#292530'][i];ctx.fillRect(mobile?25:55+i*405,mobile?top+i*134:top,mobile?430:365,mobile?110:185);ctx.fillStyle=['#b978e7','#a4ddcb','#f2c879'][i];ctx.font=mobile?'36px Arial':'42px Arial';ctx.fillText(['</>','{ }','01'][i],mobile?50:78+i*405,mobile?top+67+i*134:top+88);ctx.fillStyle='#d0c4dc';ctx.font='18px Arial';ctx.fillText(['Web development','Mobile applications','Digital experiences'][i],mobile?135:78+i*405,mobile?top+65+i*134:top+142);}const tex=new T.CanvasTexture(c);tex.encoding=T.sRGBEncoding;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();return tex;}
  const laptop=new T.Group();laptop.add(box(3.5,2.35,.12,metal,0,.28,0));laptop.add(box(3.56,2.41,.065,edge,0,.28,-.075));const laptopScreen=new T.Mesh(new T.PlaneGeometry(3.27,2.07),new T.MeshBasicMaterial({map:texture(false)}));laptopScreen.position.set(0,.3,.067);laptop.add(laptopScreen);laptop.add(box(3.8,.11,2.2,metal,0,-.96,.86));laptop.add(box(3.83,.025,2.21,edge,0,-1.025,.86));for(let row=0;row<4;row++)for(let col=0;col<12;col++){const k=box(.23,.023,.17,black,-1.51+col*.275,-.893,.3+row*.23);laptop.add(k);}laptop.add(box(1.02,.017,.52,black,0,-.89,1.55));laptop.rotation.set(-.09,-.46,-.05);devices.add(laptop);
  const phone=new T.Group();phone.add(box(.95,1.92,.15,metal));phone.add(box(1,1.96,.1,edge,0,0,-.035));const phoneScreen=new T.Mesh(new T.PlaneGeometry(.83,1.69),new T.MeshBasicMaterial({map:texture(true)}));phoneScreen.position.set(0,.01,.08);phone.add(phoneScreen);phone.add(box(.26,.045,.012,black,0,.84,.086));phone.position.set(1.8,-.34,1.15);phone.rotation.set(.03,-.24,.11);devices.add(phone);
  const ringMat=new T.MeshStandardMaterial({color:0xa66bcc,metalness:.9,roughness:.19});const arc=new T.Mesh(new T.TorusGeometry(2.65,.015,8,150),ringMat);arc.rotation.set(1.07,.25,.1);arc.position.set(0,-.28,-.9);devices.add(arc);const arc2=new T.Mesh(new T.TorusGeometry(2.8,.009,8,150),new T.MeshBasicMaterial({color:0x81998e,transparent:true,opacity:.33}));arc2.rotation.set(.2,.65,.2);arc2.position.set(0,-.1,-1.5);devices.add(arc2);
  const waterMaterial=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{uTime:{value:0},uPurple:{value:new T.Color('#ad72ce')},uMint:{value:new T.Color('#81bdae')}},vertexShader:`uniform float uTime; varying vec3 vWorld; varying float vWave;
   void main(){vec3 p=position;float wave=sin(p.x*.75+uTime*.48)*.16+cos(p.y*.86-uTime*.36)*.13+sin(p.x*.4+p.y*.62+uTime*.3)*.12;p.z+=wave;vWave=wave;vec4 world=modelMatrix*vec4(p,1.);vWorld=world.xyz;gl_Position=projectionMatrix*viewMatrix*world;}`,fragmentShader:`uniform float uTime;uniform vec3 uPurple;uniform vec3 uMint;varying vec3 vWorld;varying float vWave;
   void main(){float ripple=sin(vWorld.x*2.4+vWorld.z*1.5+uTime*.45+vWave*5.);float crest=pow(max(0.,ripple),10.);float sheen=pow(max(0.,sin(vWorld.x*.5-vWorld.z*.62+uTime*.12)),4.);float fade=1.-smoothstep(3.,13.,length(vWorld.xz));vec3 color=mix(uPurple,uMint,smoothstep(-.2,.3,vWave));color=mix(vec3(.035,.025,.06),color,crest*.55+sheen*.16);gl_FragColor=vec4(color,fade*.82);}`});
  const water=new T.Mesh(new T.PlaneGeometry(30,24,100,75),waterMaterial);water.rotation.x=-Math.PI/2;water.position.set(0,-2.05,-2);scene.add(water);canvas.dataset.water='flowing';
  let targetX=0,targetY=0,visible=true,inspecting=false,paused=reduced,dragging=false,dragX=0,dragY=0,yaw=0,pitch=0,inspectBlend=0,scrollBlend=0;
  const hero=root.querySelector('.lab-stage'),tools=root.querySelector('.scene-tools'),inspectButton=root.querySelector('#scene-inspect'),motionButton=root.querySelector('#scene-motion');tools.hidden=false;
  function motionState(){motionButton.setAttribute('aria-pressed',String(paused));motionButton.setAttribute('aria-label',paused?'Resume water and model animation':'Pause water and model animation');motionButton.title=paused?'Resume animation':'Pause animation';motionButton.textContent=paused?"Resume":"Pause";}motionState();motionButton.addEventListener('click',()=>root.querySelector('#motion-toggle').click());document.addEventListener('cp-motion',e=>{paused=e.detail;motionState();});
  function inspect(value){inspecting=value;hero.classList.toggle('inspecting',value);inspectButton.setAttribute('aria-pressed',String(value));inspectButton.setAttribute('aria-label',value?'Return to portfolio':'Inspect 3D models');inspectButton.title=value?'Return to portfolio':'Inspect 3D models';inspectButton.textContent=value?"Return":"Inspect";if(!value){yaw=pitch=0;}else canvas.focus({preventScroll:true});}
  inspectButton.addEventListener('click',()=>inspect(!inspecting));root.querySelector('#scene-reset').addEventListener('click',()=>{yaw=pitch=targetX=targetY=0;});
  hero.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||dragging||inspecting)return;const r=hero.getBoundingClientRect();targetX=(e.clientX-r.left)/r.width-.5;targetY=(e.clientY-r.top)/r.height-.5;});hero.addEventListener('pointerleave',()=>{targetX=targetY=0;});
  canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!inspecting)return;dragging=true;dragX=e.clientX;dragY=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw+=(e.clientX-dragX)*.008;pitch=Math.max(-.4,Math.min(.4,pitch+(e.clientY-dragY)*.005));dragX=e.clientX;dragY=e.clientY;canvas.dataset.rotation=yaw.toFixed(2);});function release(){dragging=false;}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
  canvas.addEventListener('keydown',e=>{if(e.key==='Escape'){inspect(false);inspectButton.focus();return;}if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.18;if(e.key==='ArrowRight')yaw+=.18;if(e.key==='ArrowUp')pitch=Math.max(-.4,pitch-.1);if(e.key==='ArrowDown')pitch=Math.min(.4,pitch+.1);canvas.dataset.rotation=yaw.toFixed(2);});
  let mobile=false;function resize(){const r=hero.getBoundingClientRect();mobile=r.width<760;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();devices.position.set(0,mobile?-.25:0,0);devices.scale.setScalar(mobile?.58:.95);laptop.rotation.y=mobile?-.23:-.46;phone.position.x=mobile?1.55:1.8;camera.position.z=mobile?10.5:10;}
  new ResizeObserver(resize).observe(hero);resize();if('IntersectionObserver'in window)new IntersectionObserver(e=>{visible=e[0].isIntersecting;},{threshold:0}).observe(hero);
  const clock=new T.Clock();let waterTime=0;function frame(){requestAnimationFrame(frame);const delta=Math.min(clock.getDelta(),.05);if(!visible||document.hidden)return;if(!paused)waterTime+=delta;waterMaterial.uniforms.uTime.value=waterTime;
   const r=hero.getBoundingClientRect(),scrollTarget=reduced?0:Math.max(0,Math.min(1,-r.top/r.height));scrollBlend+=(scrollTarget-scrollBlend)*.055;inspectBlend+=(Number(inspecting)-inspectBlend)*(reduced?1:.06);
   devices.position.x=(0)*(1-inspectBlend);devices.position.y=(mobile?-.25:0)*(1-inspectBlend)+scrollBlend*.3;devices.scale.setScalar((mobile?.58:.95)+inspectBlend*(mobile?.1:.16));camera.position.z=(mobile?10.5:10)-inspectBlend*(mobile?.4:1.1)-scrollBlend*.35;
   devices.rotation.y+=((paused?0:targetX*.2)+yaw+scrollBlend*.22-devices.rotation.y)*.06;devices.rotation.x+=((paused?0:-targetY*.1)+pitch-scrollBlend*.05-devices.rotation.x)*.06;
   laptop.position.y=Math.sin(waterTime*.55)*.065;laptop.rotation.z=-.05+Math.sin(waterTime*.35)*.018;phone.position.y=-.34+Math.sin(waterTime*.7+1)*.09;arc.rotation.z=waterTime*.025;renderer.render(scene,camera);
  }frame();
 };
window.cpDevInitScene();})();
